### ISSUE TITLE
Doppelbiereingaben

### ISSUE THREAD

**Issue by uek390** [marxxxx/beerkoenig#10]
doppelte Eingabe von Bier soll nicht möglich sein.
hinweis soll bei speichern kommen und endgültige übermittlung nicht möglich

**Comment by marxxxx** [comment]
Denke wir sollten das nur dahingehend ändern, dass doppelt erfasste Biere in der Geschmackswertung nicht doppelt gezählt werden. Während der Abstimmungsphase wechselt man ja ggf. öfters seine Meinung und man sollte hier in der Eingabe nicht behindert werden.
Speichern ist aktuell nicht mehr nötig. Es wird im Hintergrund bei jeder Änderung gespeichert.

**Comment by uek390** [comment]
is a recht... oba donn miassats beim bierranking an mittelwert aus abgegebener punkte nehma... sonst kriagt vielleicht des beste bier zwenig punkte, weil se irgendwer bei da eingabe verhaut

**Comment by marxxxx** [comment]
ok Mittelwert geht auch. aktuell wird der Maximalwert verwendet wenn es mehrere zum selben vier gibt

Am 01.11.2018 13:40 schrieb uek390 <notifications@github.com>:

is a recht... oba donn miassats beim bierranking an mittelwert aus abgegebener punkte nehma... sonst kriagt vielleicht des beste bier zwenig punkte, weil se irgendwer bei da eingabe verhaut

**Comment by uek390** [comment]
i glaub, des woa jetzt eh a denkfehler. die note is ja eh für des wiakliche bier und net für des vom user eingegebene bier.
und do wär a maximalwert eh wurscht, weils eh ka doppelt serviertes bier gibt.
