### ISSUE TITLE
punkteauflösung 

### ISSUE THREAD

**Issue by uek390** [marxxxx/beerkoenig#12]
anstatt das ergebnis auf einmal so hinzuklatschen, wärs cool, wenn die rangliste vom schlechtesten bis zum besten nacheinander mit verzögerung (z.b. 15 sekunden mit anzeige von bieren gewusst/bieren nicht gewusst) eingeblendet wird.
das würde die auflösung spannender machen.

**Comment by marxxxx** [comment]
Ist umgesetzt in aktueller Version inklusive dramatischem Countdown und Animation.
